# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Timelanguage < Formula
  desc "A language to manage time"
  homepage "https://github.com/bymarkone/timelanguage.git"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bymarkone/timelanguage/releases/download/v0.1.0/timelanguage_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "e65c58b6a6a3a2264250f23e520822d105eb77561c2ddec206be35f158029d33"

      def install
        bin.install "timelanguage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/bymarkone/timelanguage/releases/download/v0.1.0/timelanguage_0.1.0_Linux_armv6.tar.gz"
      sha256 "b199c6355ea05e82d651a511cc40808c1b1cf6ccbd71ababee97db85a876104a"

      def install
        bin.install "timelanguage"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bymarkone/timelanguage/releases/download/v0.1.0/timelanguage_0.1.0_Linux_x86_64.tar.gz"
      sha256 "26e9223c21ee3c6e433baedf9541edcf9ae2a73621e1f84705d6b9d3d2089dca"

      def install
        bin.install "timelanguage"
      end
    end
  end

  depends_on "go" => :optional
  depends_on "git"
end
